# Generated by Django 6.0.4 on 2026-05-08 05:13

import django.core.validators
import envios.vaidators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encomienda',
            options={},
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='peso_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[envios.vaidators.validar_peso_positivo, django.core.validators.MinValueValidator(0.01)]),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='encomienda',
            table=None,
        ),
    ]
