# Generated by Django 6.0.4 on 2026-05-08 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('envios', '0002_alter_encomienda_options_alter_encomienda_codigo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['apellidos', 'nombres']},
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recibidos', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encomiendas', to='envios.empleado'),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enviados', to='clientes.cliente'),
        ),
    ]
